name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'

defaults:
  run:
    working-directory: ./mlops_demo

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}

jobs:
  prod:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate
        id: validate
        run: |
          databricks bundle validate -t pl_mlops_demo_prod
      - name: Deploy
        id: deploy
        run: |
          databricks bundle deploy -t pl_mlops_demo_prod
      - name: Run Feature Engineering Workflow
        id: feature_engineering
        run: |
          databricks bundle run feature_engineering_job -t pl_mlops_demo_prod
      - name: Run Training Workflow
        id: training
        run: |
          databricks bundle run training_job -t pl_mlops_demo_prod
