# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under ulta_mlops_demo/resources/*
# and ulta_mlops_demo/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'

defaults:
  run:
    working-directory: ./ulta_mlops_demo

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}

jobs:
  prod:
    concurrency: ulta_mlops_demo-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate
        id: validate
        run: |
          databricks bundle validate -t ulta_mlops_demo_prod
      - name: Deploy
        id: deploy
        run: |
          databricks bundle deploy -t ulta_mlops_demo_prod
      - name: Run Feature Engineering Workflow
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t ulta_mlops_demo_staging
      - name: Run Training Workflow
        id: training
        run: |
          databricks bundle run model_training_job -t ulta_mlops_demo_staging
