name: CI
on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: ./ulta_mlops_demo/

env:
  STAGING_DATABRICKS_TOKEN: ${{ secrets.STAGING_DATABRICKS_TOKEN }}
  PROD_DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  integration_tests:
    needs: unit_tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate
        id: validate
        env:
          DATABRICKS_TOKEN: ${{ env.STAGING_DATABRICKS_TOKEN }}
        run: |
          databricks bundle validate -t ulta_mlops_demo_staging
      - name: Deploy Staging
        id: deploy
        env:
          DATABRICKS_TOKEN: ${{ env.STAGING_DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy -t ulta_mlops_demo_staging
      - name: Run Feature Engineering Workflow
        id: feature_engineering
        env:
          DATABRICKS_TOKEN: ${{ env.STAGING_DATABRICKS_TOKEN }}
        run: |
          databricks bundle run write_feature_table_job -t ulta_mlops_demo_staging
      - name: Run Training Workflow
        id: training
        env:
          DATABRICKS_TOKEN: ${{ env.STAGING_DATABRICKS_TOKEN }}
        run: |
          databricks bundle run model_training_job -t ulta_mlops_demo_staging

  prod_validation:
    needs: integration_tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate
        id: validate
        env:
          DATABRICKS_TOKEN: ${{ env.PROD_DATABRICKS_TOKEN }}
        run: |
          databricks bundle validate -t ulta_mlops_demo_staging    
